# file: nagios-server/handlers/main.yml

- name: Reload Nagios
  service:
    name: "{{ nagios_service }}"
    state: reloaded

- name: Reload NSCA
  service:
    name: "{{ nsca_service }}"
    state: reloaded

- name: Restart Apache
  service: name=apache2 state=restarted
  when: nagios_a2_config

- name: Reload Apache
  service: name=apache2 state=reloaded
  when: nagios_a2_config
