---
- hosts: all

  vars:
    sonar_web_context: "/sonar"
    mysql_python_package_debian: python3-mysqldb

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install dependencies.
      package:
        name:
          - curl
          - unzip
        state: present

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.mysql
    - role: geerlingguy.sonar

  post_tasks:
    - name: Ensure SonarQube is running.
      uri:
        url: "http://172.31.59.48:9000{{ sonar_web_context }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
