---

- name: Configure Nagios CGI
  template: src=/home/ubuntu/Roles/roles/nagios/templates/trusty/cgi.cfg.j2
        dest={{ nagios_cgi_file }}
        owner=root group=root mode=0644
        backup=yes
  notify: Reload Nagios
