---

- name: Check if sdkman is installed

  shell: test -d {{sdkman_folder}} && echo "yes" || echo "no"

  register: is_sdkman_installed



- name: Install SDKMAN!

  when: is_sdkman_installed.stdout == "no"

  shell: curl -s {{sdkman_script_install_url}} | bash executable=/bin/bash

  become: no



- name: Ensure presence of bashrc

  file: state=touch path={{user_home_path}}/.bashrc

  become: no



- name: Add sdkman in .bashrc

  lineinfile: dest={{user_home_path}}/.bashrc regexp="\/.sdkman/bin\/sdkman\-init\.sh" line='[[ -s "{{sdkman_folder}}/bin/sdkman-init.sh" && ! $(which sdkman-init.sh) ]] && source "{{sdkman_folder}}/bin/sdkman-init.sh"

  become: no



- name: Installing gradle

  # This will read your bash profile file, which would setup sdkman-init.sh.

  command: bash -lc "sdk install gradle {{gradle_version}}"

  become: no
